### ISSUE TITLE
Suggestion: every other row

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/WelcomeListBox-EvoDashboard-Plugin#1]
Highlight every other row like "Recently edited/created Resources" box.

![my evolution site evo cms manager2](https://user-images.githubusercontent.com/6113504/28743926-060d2012-744e-11e7-99e4-430884ffb137.png)

**Comment by Nicola1971** [comment]
added in latest fix
![download](https://user-images.githubusercontent.com/7342798/28790588-ff4a0a5a-7629-11e7-87b8-6dcf2a479b43.png)

**Comment by risingisland** [comment]
Awesome, thanks.
